### PR TITLE
Version native library, allowing developers to easily switching among multiple versions

### PR DESCRIPTION
**Pull request by kvr000**
This adds native version suffix to zstd-jni native library. It's especially useful when library is not among supported platforms and developers need to compile and maintain the native library in their library directories. This allows them switching easily among multiple runtime versions, without solving conflicts or changing library paths.

### CODE REVIEW

**Comment by luben** [comment]
Hi,

Sorry for the delay looking into it. LGTM. I am not sure if there is any value to track the native version separately from the main version. In any case the binaries will be embedded in the jar, so making the native library version the same as the jar version will make sure that the library will be loaded from the same jar. Also it will makes sure we don't forget to bump the native version.

There is `version` file in the root of the project. What's your opinion?

**Comment by kvr000** [comment]
I expected the native version to be more stable than the java code and therefore the developers won't need to update it as often.  Not sure how much true this statement is though.  I'm good updating to use version instead of NativeVersion if you think it's not worth having two.

**Comment by luben** [comment]
Yes, let's use the same version. Separate version would make sense if the native library is distributed separately.

**Comment by kvr000** [comment]
Ok, updated.  Thanks!

**Pull request merged**
