### PR TITLE
Add new qemu platform for riscv64

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Hi,
Can you help to review this simple patch trying to [add riscv64 CI support](https://github.com/luben/zstd-jni/issues/284) in github?
Hope I'm doing it correctly.
Thanks!

### CODE REVIEW

**Comment by Hamlin-Li** [comment]
CI failed.
Seemed the reason is can not pull the docker image from repository:
```
$ docker image pull riscv64/eclipse-temurin:11-jdk-focal
Error response from daemon: pull access denied for riscv64/eclipse-temurin, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by Hamlin-Li** [comment]
The root cause should be, there is no riscv64 jdk release at https://adoptium.net/en-GB/temurin/releases/ yet.

**Comment by luben** [comment]
Yes, looks like we need another JDK distribution for risk V to work

**Comment by luben** [comment]
I also don's see RiskV support in https://www.azul.com/downloads/?package=jdk#zulu

I will close that PR for better times when we get upstream JDK for RiskV

**Comment by Hamlin-Li** [comment]
Yes, let's find the upstream JDK for riscv first.

**Pull request closed without merging**
