### PR TITLE
Allow pre-allocated Ctx

### PR DESCRIPTION
**Pull request by mortengrouleff**
For directbuffer variants with dict for lower allocation effect.

Note that the measurements of allocations do not track the native ones, which includes the new Ctx malloc'ed when not provided.

### CODE REVIEW

**Comment by luben** [comment]
Hi,

Sorry for the late reply, I was traveling.

LGTM but I have a few comments.

- I would prefer to keep the existing `Zstd` static method signatures as they are. With the proposed changes we will break customer code as we add new parameters to existing methods.

- I was also thinking how to add support for the new APIs that reuse the compression/decompression context between requests. I think we should not add the new compression/decompression methods as static methods on `Zstd` (it's already quite heavy) but as proper methods on `ZstdCompressCtx` and `ZstdDecompressCtx`. For example, instead of `Zstd.compress(..., cctx)` we will have `cctx.compress(...)`

**Comment by mortengrouleff** [comment]
Yes, you're absolutely right.

I'll rework to your suggested API, and force-push a change.

**Comment by luben** [comment]
Great, thanks!

**Comment by alexwang08** [comment]
Just curious will this feature be integrated soon?

**Comment by mortengrouleff** [comment]
> Just curious will this feature be integrated soon?

I still plan on doing the suggested changes to the API before merging. No ETA.

**Comment by mortengrouleff** [comment]
I've refactored the API. 
This has no changes to any existing API.
Rather it adds new methods on the new context classes.

**Comment by luben** [comment]
LGTM. I will review in detail and merge early next week.

**Comment by luben** [comment]
Looks great. Thanks a lot for the contribution. I will follow next week with small tweaks, e.g. fix the shared log exception messages not to refer to dictionaries.

**Comment by luben** [comment]
@mortengrouleff , I have pushed a continuation of the contexts support, still just for ByteBuffers. Can you look if it will fit your use case? The difference is that the dictionary is attached to the context and not supplied on each compression or decompression request.

If it works for you, I am inclined to move forward only with these new methods. Here are my reasons:
- passing parameters to compression/decompression leads to combinatorial explosion of variants - `Zstd` class looks quite confusing for this reason.
- most of the old low-level functions have limitations, e.g.:
```
/*! ZSTD_compress_usingCDict() :                                                                                                                                                                                                               
 *  Note : compression level is _decided at dictionary creation time_,
 *     and frame parameters are hardcoded (dictID=yes, contentSize=yes, checksum=no) */
```
- attaching params to context compose better.

Any feedback is welcome,
luben

**Comment by mortengrouleff** [comment]
Yes. That sounds like a good plan.

From the commits it looks like it's possible to switch to another dict reusing the same context. That should ensure the same low allocation load as the initial PR allowed, while being easier to use.
Having the `loadDict(ZstdDictDecompress dict)` is the crucial point I guess.
BTW: Why not have those be a void functions, as they can only return `0` or throw an exception.

**Comment by luben** [comment]
Good point about making them `void`. Yes, dictionaries can be switched and removed dynamically.

**Comment by luben** [comment]
@mortengrouleff , I pushed a cleanup commit and switched tests. I will release soon, as I already imported zstd-1.4.4 the weekend, just waiting for them to announce the release.

**Comment by mortengrouleff** [comment]
why is there a level on the c_ctx, isn't that set in stone when creating the dict to use?

**Comment by luben** [comment]
@mortengrouleff it looks the level is picked by the CCtx. I was not expecting in neither, but also makes sense.

**Comment by mortengrouleff** [comment]
Ahh, okay. Makes sense then.
I wonder if the levels need to match, or if there may be a point in using a higher level when creating the dict than when applying it, as that may take a bit of extra time for the dict-build, but then be more efficient on the (say) 1000 invocation of compress that follow...

**Comment by mortengrouleff** [comment]
Looking forward to trying out this new release!

**Comment by luben** [comment]
Looks the levels don't need to match. Also I don't see any difference in speed or compression ration depending on the dictionary compression level.

**Comment by luben** [comment]
Just pushed it. It should be available on Maven central soon.

**Pull request merged**
