### PR TITLE
Increment version number to reflect additional API

### PR DESCRIPTION
**Pull request by anelson**
SemVer guidelines dictate that the addition of new API functionality that is non-breaking, like the change in PR #17, increment the minor version number.  This will also ensure the updated bits are resolved via Maven Central regardless of aggressive caching by intermediate proxies like Artifactory.

### CODE REVIEW

**Comment by luben** [comment]
I am releasing the zstd-jni with the version of the zstd it is based on. Currently zstd is releasing once per month or so. I think this is reasonable schedule for the zstd-jni release also.

**Comment by anelson** [comment]
I see.  I need to build and publish this updated version to my private repository before then.  I tried building it myself but I can't figure out how you produce the JAR bundle with multiple platform binaries in it.  I can build any one platform but I'm trying to build a combined bundle with Linux amd64 and OS X support.  Any hints for me?

**Comment by luben** [comment]
Yes, the assembly of the final jar is a manual process involving multiple machines. I have some automation around my setup. Here is what you can do:

1. on Linux and Mac OS X:  "sbt clean compile test"
2. copy "target/classes/darwin/x86_64/libzstd.dylib" from the OS X dir to the Linux one (in the same place).
3. on the Linux: "sbt publishLocal"

The resulting jar will be in "~/.ivy2/local/com.github.luben/zstd-jni/1.1.0"

**Comment by anelson** [comment]
That makes sense, thanks!

**Comment by luben** [comment]
I released v1.1.1 yesterday with all the additions since 1.1.0

**Pull request closed without merging**
