### PR TITLE
Add dictionary support.

### PR DESCRIPTION
**Pull request by nishemon**
Three methods compressUsingDict,decompressUsingDict and trainFromBuffer are added to Zstd class.
And the directory src/main/native/dictBuilder from https://github.com/Cyan4973/zstd.

### CODE REVIEW

**Comment by luben** [comment]
Great contribution!

Is it going to work if we load the dictionary from file, e.g. a dictionary produced by the zstd --train command?

**Comment by luben** [comment]
Implements #3

**Comment by nishemon** [comment]
Thanks.

It is yes, zstd --train generate a plain binary data (maybe it is merely a concatenation of common substrings), so we can use the whole bytes like the return of java.nio.file.Files.readAllBytes() as a dictionary.

**Comment by luben** [comment]
merged, I will add more utility functions on top you your, e.g. to compress whole buffers, without offset and length

**Pull request merged**
