### PR TITLE
Add new qemu platform for riscv64 - 2nd try

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Hi,
Can you help to review this simple patch trying to https://github.com/luben/zstd-jni/issues/284 in github?
(This is the 2nd try of https://github.com/luben/zstd-jni/pull/285)
Thanks!

### CODE REVIEW

**Comment by luben** [comment]
that doesn't look to work and also breaks the s390x tests

**Comment by Hamlin-Li** [comment]
Yes, both riscv and s390x encountered below issue:
```
/github_workspace/sbt-java-module-info /github_workspace
Downloading sbt launcher for 1.9.0:
  From  https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.9.0/sbt-launch-1.9.0.jar
    To  /root/.sbt/launchers/1.9.0/sbt-launch.jar
Downloading sbt launcher 1.9.0 md5 hash:
  From  https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.9.0/sbt-launch-1.9.0.jar.md5
    To  /root/.sbt/launchers/1.9.0/sbt-launch.jar.md5
cat: /root/.sbt/launchers/1.9.0/sbt-launch.jar.md5: No such file or directory
md5sum: 'standard input': no properly formatted MD5 checksum lines found
Checksum does not match
Could not download and verify the launcher. Obtain the jar manually and place it at /root/.sbt/launchers/1.9.0/sbt-launch.jar
Error: Process completed with exit code 1.
```

But I can access `https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.9.0/sbt-launch-1.9.0.jar.md5`.
Not sure what causes the issue.

**Comment by Hamlin-Li** [comment]
Seems we still face the same issue.

**Comment by luben** [comment]
Fails again. s390 workflow getting cancelled due to the other task failure. Can you add `strategy: fail-fast: false` to let it run to completion?

**Pull request closed without merging**
