### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by mkane007**
Windows 8.1/10 build supported
Project structure improved

### CODE REVIEW

**Comment by luben** [comment]
Looks good but I have some points I want to discuss:

- I don't like committing the binaries in the repository - in this way they will be out of sync most of the time. Do you have any recommendation how to keep the binary updated with the new releases?

- I will apply the dot conversion for the os name. Maybe we also want to abbreviate the windows OS names to "win" only - I don't think there will be any difference between win2000 - win10 regarding the functionallity of the package: it does not depend on anything of the OS except malloc.

- I will keep the version to 0.5.0 - let's keep it the same as the upstream zstd library.

I am thinking on working on some integration with https://www.appveyor.com/ for windows builds so that it can produce the libraries and upload the artifact that I can include in the maven release (I do the same for Mac OS X with TravisCI). Do you have any better ideas?

**Comment by mkane007** [comment]
1. Binaries removed
2. Agree about Windows versions
3. Reverted to 0.5.0
Travis-CI would support Windows in a few. But you have platforms like netbsd and aix. I'd suggest to setup Vagrant environment with different vagrantfiles for different supported OS. But it would take long time to se this env up. Maybe we need to define which OS we need to support first?

**Comment by luben** [comment]
I am building these versions on the gcc compile farm - it uses an external script that is not committed in the repo.

Please distregard the above appveyor failures - I have not yet figured it out

**Comment by luben** [comment]
Hi,

I am closing this one. Thanks for helping me figure out some of the road blocks. The builds and tests on appveyor now pass for both win32 and win64 and I will release updated package shortly.

Regards,

**Pull request closed without merging**
