### PR TITLE
Implemented a streaming version of the DirectBuffer decompress and compress methods

### PR DESCRIPTION
**Pull request by DavyLandman**
As discussed in #27, you might want to avoid allocating a large enough target buffer to decompress the whole file into. This pull requests implements the `ZstdDirectBuffer(Decompressing/Compressing)Stream` (open for a better name) classes. The decompressor you initialize with the full buffer (like in the case of a memory map), and the compressing version you pass it a buffer and have to implement the flushing yourself.

You can then decompress that stream to another (direct) ByteBuffer of any size, until the whole stream is read and there are no more bytes to be decompressed.

For compressing you only have to implement an abstract method that takes care of flushing the buffer and either returning the same buffer, or creating a new one (as you would expect for a memory map)

I've copied and adapted the tests that seemed relevant, and also copied the benchmark code.

### CODE REVIEW

**Comment by DavyLandman** [comment]
I've just implemented a compressor variant. it's an abstract class, and you only have to take care to flush the buffer when needed. I think it's quite elegant. And supports both normal buffered streaming or memory mapping with a moving region.

**Comment by DavyLandman** [comment]
I might update the interface of the Decompressor to also have an abstract method that handles the request for more data. In that way both use cases can be supported.

**Comment by DavyLandman** [comment]
please keep this pull request open a bit longer, I welcome feedback off course! But I want to add some more tests around the streaming API, to actually tests limits of them.

**Comment by luben** [comment]
Yes, sure. It looks good to me. The only recommendation: can you check that the supplied ByteBuffers are actually DirectByteBuffers (.is_direct) in the java code as you assume that they are in the JNI code.

Also I was thinking if we can make the compressor non-abstract, i.e. the provided flush method to be noop (as there are not common behavior)  but let the user override it or if he prefer to drive the flushing outside of the stream compression.

**Comment by DavyLandman** [comment]
I think I'm done. I've removed the abstract methods and implemented defaults, for the decompressor I completely agree, for the compressor, not that sure.

So waiting for your feedback, but I would say ready to merge ;)

**Comment by luben** [comment]
Thanks a lot for the contribution. Just merged it.

**Pull request merged**
