### PR TITLE
Add new constructor to ZstdDictCompress and ZstdDictDecompress

### PR DESCRIPTION
**Pull request by mortengrouleff**
that allows the byReference semantics for the provided byte buffer: If you set this to true, you avoid the copying of the dict data into a natively malloc'ed buffer, but then also have to promise that the byte buffer will not be modified before the CTX has been closed.

### CODE REVIEW

**Comment by mortengrouleff** [comment]
Hi @luben 

Thanks for your continuing efforts to maintain this library.

I'd like to add this slight API extension that allows not triggering a copy-operation in the native layer, but instead letting the native layer use the direct byte buffer it was supplied for the dict. The native zstd already has this feature as "ByReference" methods. The purpose is to avoid the external `malloc` that is incurred by the native code for the existing way of accessing the dict, by instead allowing the application to keep a pool of direct buffers.

The refactor has been done in a manner that should be 100% compatible with existing clients.

The new "get" method for the shared buffer reference is to make it easy for the client application to get the proper reference that it needs to either "free" or "return to pool" just before it closes the CTX instance. If the field was not accessible, client apps would need to track this ref along with the CTX ref.

**Comment by luben** [comment]
LGTM, thanks for the contribution!

**Comment by luben** [comment]
Sure, I bumped the version earlier today for some build system changes and I can release it later today or tomorrow.

**Comment by luben** [comment]
Published 1.5.6-2

**Pull request merged**
