### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/luben/zstd-jni/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
You can also check the alerts discovered by [LGTM](https://lgtm.com/projects/g/luben/zstd-jni).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by luben** [comment]
LGTM

**Comment by xcorail** [comment]
Hi @luben 
Please check [here](https://lgtm.com/blog/announcing_project_badges), at the end

> Because we're using Shields.io, these badges are entirely customizable. You can, if you wish, change their style, colors and label. Instructions are available on their website.

**Comment by luben** [comment]
Thanks, great! Another quick question: is there any way to initiate a new analysis of the code base? I pushed a commit fixing some of the warnings. When should I expect it to be reflected?

**Comment by xcorail** [comment]
Our infrastructure analyses all the commits. So your commit will be analysed, you don't need to push any command. The time depends on the activity, because the priority is given to 
1. Pull requests
2. HEAD commit of each project
3. passed commits (most recent first)

**Comment by luben** [comment]
Great, thanks!

**Comment by xcorail** [comment]
@luben one precision: 
* PR are analyzed right away
* commits are polled from the repo once a day, so there is a delay here

**Pull request merged**
